stages:
  - build
  - docker
  - deploy

variables:
  APP_NAME: springboot-app
  NEXUS_IP: 192.168.58.2   # minikube ip
  NEXUS_PORT: "30387"           # Nexus Docker NodePort
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  DOCKER_TLS_CERTDIR: ""

###Maven Build Stage
maven-build:
  stage: build
  image: maven:3.9-eclipse-temurin-17
  script:
    - git clone https://github.com/ahmedmisbah-ole/Devops-Orange.git
    - cd Devops-Orange
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - Devops-Orange/target/*.jar
    expire_in: 1 hour

###Docker Build & Push to Nexus
docker-build-push:
  stage: docker
  image: docker:25
  services:
    - docker:25-dind
  dependencies:
    - maven-build
  script:
    - cd Devops-Orange
    - docker build -t $APP_NAME:$IMAGE_TAG .
    - docker login $NEXUS_IP:$NEXUS_PORT -u admin -p admin123
    - docker tag $APP_NAME:$IMAGE_TAG $NEXUS_IP:$NEXUS_PORT/$APP_NAME:$IMAGE_TAG
    - docker push $NEXUS_IP:$NEXUS_PORT/$APP_NAME:$IMAGE_TAG

###Manual Helm Deploy (Dev/Test)
helm-deploy:
  stage: deploy
  image: alpine/helm:3.15.0
  when: manual

  variables:
    ENV:
      value: dev
      options:
        - dev
        - test
      description: "Choose target namespace"

  script:
    - echo "Deploying Spring Boot application to $ENV namespace"

    - helm upgrade --install springboot-app helm/springboot-app \
        --namespace $ENV \
        --create-namespace \
        --set image.repository=$NEXUS_IP:$NEXUS_PORT/$APP_NAME \
        --set image.tag=$IMAGE_TAG


